id: 
name: GitOps.PullRequestIssueManagement
description: GitOps.PullRequestIssueManagement primitive
owner: 
resource: repository
disabled: false
where: 
configuration:
  resourceManagementConfiguration:
    scheduledSearches: []
    eventResponderTasks:
    - if:
      - payloadType: Issue_Comment
      - isAction:
          action: Created
      - isActivitySender:
          issueAuthor: True
      - hasLabel:
          label: Needs Author Feedback
      then:
      - addLabel:
          label: 'Needs Attention :wave:'
      - removeLabel:
          label: Needs Author Feedback
      description: 
onFailure: 
onSuccess: 
